function constructGadget(type) { const icons = document.getElementById('icons');
  if (type === 'footballclock') {
const A=document.createElement("div");A.classList.add("gadget"),A.id="footb",A.style.left="24px",A.style.top="266px",A.style.backgroundImage="url(laptop/widget_ball00.gif)",A.style.width="160px",A.style.height="100px",A.style.filter="",A.style.color="#3f3",A.style.textShadow="0 -1px 5px",A.style.fontFamily="clock";const td=document.createElement("span");td.classList.add("td"),td.style.position="absolute",td.style.left="46px",td.style.bottom="41px",td.style.fontSize="16px",td.style.transform="scaleY(125%)",td.style.letterSpacing="-.5px";const fbcd=document.createElement("span");fbcd.id="fbcd",fbcd.style.position="absolute",fbcd.style.left="46px",fbcd.style.bottom="27px",fbcd.style.fontSize="12px",fbcd.style.letterSpacing="-1.5px",fbcd.style.textAlign="center",fbcd.style.width="68px",fbcd.textContent=new Date(new Date().setDate(new Date().getDate()+2)).toLocaleDateString("en-US",{weekday:"short"}).toUpperCase()+" "+new Date().toLocaleDateString("en-US",{day:"2-digit",month:"short"}).toUpperCase(),A.appendChild(td),A.appendChild(fbcd),icons.appendChild(A);
  }
  if (type === 'meter') {
const meter=document.createElement("div");meter.id="meter",Object.assign(meter.style,{paddingLeft:"2px",fontFamily:"neuropolitical",fontSize:"12px",textShadow:"3px 1px 3px, #000 -1px 2px 1px, #000 1px -1px 0",display:"flex",flexDirection:"column",backgroundImage:"url(laptop/widget_metr02.gif)",width:"128px",height:"90px",left:"399px",bottom:"382px"}),meter.classList.add("gadget");const bg1=document.createElement("img");Object.assign(bg1.style,{position:"absolute",left:"65px",top:"45px"}),bg1.src="laptop/widget_metr01.gif";const bg2=document.createElement("img");Object.assign(bg2.style,{position:"absolute",left:"65px",top:"45px",mixBlendMode:"screen",opacity:".5"}),bg2.src="laptop/widget_metr02.gif";const title=document.createElement("div");function makeBar(e,t,i){let a=document.createElement("div");Object.assign(a.style,{color:t,display:"flex",justifyContent:"space-between",borderBottom:"solid 1px #000",outline:"solid 1px #555",lineHeight:`${i}px`,height:`${i}px`,marginTop:"-1px"});let l=document.createTextNode(e),r=document.createElement("canvas");return r.classList.add("metercanvas"),r.width=85,r.height=i,r.style.background="url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAgMAAAC5YVYYAAAADFBMVEUAAAAAAABHcEwAAAAPpAoIAAAABHRSTlMwVAB6mN2AdQAAABVJREFUCNdjCAhmyFrNoIWEgNz//wFSDAggjls/PwAAAABJRU5ErkJggg==),linear-gradient(#000, #222)",a.appendChild(l),a.appendChild(r),a}Object.assign(title.style,{color:"#2ff",width:"100%",borderBottom:"solid 1px",margin:"2px",background:"#fff6"}),title.textContent="Process Meter",meter.appendChild(bg1),meter.appendChild(bg2),meter.appendChild(title),meter.appendChild(makeBar("CPU","#f60",30)),meter.appendChild(makeBar("Net.","#7d3",20)),meter.appendChild(makeBar("Disk","#43f",20)),icons.appendChild(meter); const M_canvases = meter.querySelectorAll(".metercanvas");M_canvases.forEach(e=>{window.METER_REGISTER&&window.METER_REGISTER(e)});
  }
}
window.addEventListener("message",e=>{e.data?.type==="GADGET_footballclock_trigger"&&(localStorage.getItem("GADGET_footballclock")||(traction("CPU",5,256),traction("Net.",8,768),setTimeout(()=>{let e=document.querySelector("#browser");if(e){let t=document.createElement("span");t.className="downloadnotice",t.innerHTML="&#128456; - Football_Clock.gaj",t.style.transform="translateY(-2px)",t.onclick=()=>{localStorage.setItem("GADGET_footballclock","true"),localStorage.setItem("mdnverse","true"),t.remove()},e.appendChild(t),new Audio("/laptop/pianos02.ogg").play(),localStorage.setItem("gadgets_on_desktop",!0)}},512)))});
window.addEventListener("message",e=>{e.data?.type==="PROGRM_maddenonline_trigger"&&(traction("CPU",3,3072),traction("Net.",8,2048),traction("Disk",6,1024),setTimeout(()=>{let e=document.querySelector("#browser");if(e){let n=JSON.parse(localStorage.getItem("applications")||"[]");if(!n.includes("MaddenOnline.exe;Maddenverse")){let a=document.createElement("span");a.className="downloadnotice",a.innerHTML="&#128456; - MaddenOnline.exe",a.style.transform="translateY(-2px)",a.onclick=()=>{a.remove(),setTimeout(()=>location.reload(),256)},e.appendChild(a),new Audio("/laptop/pianos02.ogg").play(),localStorage.setItem("applications",JSON.stringify([...n,"MaddenOnline.exe;Maddenverse"]))}}},512))});
function LG() {window.M_variables=window.M_variables||{CPU:0,"Net.":0,Disk:0},window.meterCanvases=window.meterCanvases||[],window.moduptick=(a,e)=>{window.M_variables[a]=e};window.METER_REGISTER=e=>{window.meterCanvases.push(e)};
if("true"===localStorage.gadgets_on_desktop)for(let key in localStorage)key.startsWith("GADGET_")&&"true"===localStorage[key]&&constructGadget(key.slice(7));
  if (!window.METER_STARTED) { window.METER_STARTED = true;
  function M_bar(t,e){let i=t.closest("div").textContent.trim(),n=window.M_variables[i]||0,r=Math.random()*(.1*t.height)+(.8*t.height+3*n)/2-6;return{x:t.width,y:r,width:e,speed:1}}
  function animate(){if(!window.METER_PAUSED)for(let e of window.meterCanvases){let t=e.getContext("2d");t.clearRect(0,0,e.width,e.height),(!e.bars||0===e.bars.length||e.bars[e.bars.length-1].x<e.width-7)&&(e.bars=e.bars||[],e.bars.push(M_bar(e,8))),e.bars.forEach(e=>e.x-=e.speed),e.bars=e.bars.filter(e=>e.x+e.width>0);let a=getComputedStyle(e.closest("div")),r=a.color;e.bars.some(e=>e.y>20)&&(r="#f00"),t.fillStyle=r,t.beginPath(),e.bars.forEach((a,r)=>{let s=a.x+a.width/2,h=e.height-a.y;if(0===r)t.moveTo(s,h);else{let i=e.bars[r-1],l=i.x+i.width/2,b=e.height-i.y,o=(l+s)/2;t.quadraticCurveTo(l,b,o,(b+h)/2)}})/*,console.log("RENDERING")*/;let s=e.bars[e.bars.length-1].x+e.bars[e.bars.length-1].width/2,h=e.bars[0].x+e.bars[0].width/2;t.lineTo(s,e.height),t.lineTo(h,e.height),t.closePath(),t.fill()}}
  setInterval(animate, 64)}const m=document.querySelectorAll(".metercanvas");m.forEach(e=>{window.METER_REGISTER(e)});
}
document.querySelector("#ctext i").onclick=()=>{let e="true"!==localStorage.gadgets_on_desktop;localStorage.gadgets_on_desktop=e,prg03.play(),window.METER_PAUSED=!e;document.querySelectorAll(".gadget").forEach(g=>g.remove());
if(e)LG()};LG();

function L_i(t){t.forEach(t=>{let e=new Image;e.onload=()=>e.src=t});}function L_s(e){e.forEach(e=>{let n=new Audio;n.src=e})};function L_j(c){c.forEach(c=>fetch(c))}
let manifestappsopen = false;
const PRG_MANIFEST={Maddenverse:{name:"Maddenverse",width:420,height:315,top:0,right:56,id:"mdnonline",source:"init.php",splash:"/laptop/versesplash.gif"},Conductor:{name:"The Conductor",width:328,height:128,top:69,right:69,id:"theconductor",source:"edgar.html",splash:"/laptop/conductorsplash.gif"}};
function launch(e){if(manifestappsopen)return;if(e==="Maddenverse"&&!JSON.parse(localStorage.getItem("applications")||"[]").some(t=>t.split(";")[1]===e))return;manifestappsopen=!0,traction("Disk",9,256),traction("CPU",5,768),traction("Disk",5,2048),traction("Net.",8,512);traction("CPU",4,999999);traction("Disk",3,999999);let t=PRG_MANIFEST[e];
if("Maddenverse"===e){let p="laptop/madden/";fetch(p+"pl.json").then(r=>r.json()).then(({li,ls,lj})=>{L_i(li.map(f=>p+f));L_s(ls.map(f=>p+f));L_j(lj.map(f=>p+f))})}
  setTimeout(()=>{i=document.createElement("div"),s=document.createElement("img");s.style="top:190px;right:30px;position:absolute;z-index:5",s.src=t.splash,i.className="window",i.id=t.id,i.title=t.name,i.style=`width:${t.width}px;height:${t.height}px;top:${t.top}px;right:${t.right}px;position:absolute`,i.innerHTML=`<span class="windowtitle">${t.name}</span><span class="closebtn osbtn" onclick="closeprg('${e}')">X</span><iframe width="${t.width}" height="${t.height}" frameborder="0" src="laptop/${t.source}" style="zoom:.5;width:200%;height:100%"></iframe>`,document.querySelector("#dtbg").appendChild(s),setTimeout(()=>{s.remove(),document.querySelector("#dtbg").appendChild(i),traction("CPU",6,512),traction("Net.",9,768)},2048)},256)}
function closeprg(e){traction("CPU",-4,999999);traction("Disk",-3,999999);let t=PRG_MANIFEST[e];if(!t)return;let r=document.getElementById(t.id);if(r){let l=r.querySelector("iframe");l&&(l.src="about:blank"),r.remove()}manifestappsopen=!1}